# Generated by Django 6.0.1 on 2026-02-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crime", "0002_remove_complaint_is_confirmed_by_cadet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crime",
            name="level",
            field=models.CharField(
                choices=[
                    ("1", "level_1"),
                    ("2", "level_2"),
                    ("3", "level_3"),
                    ("4", "critical"),
                ],
                max_length=50,
            ),
        ),
    ]
