# Generated by Django 6.0.1 on 2026-02-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crime", "0003_alter_crime_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crime",
            name="level",
            field=models.CharField(
                choices=[
                    ("1", "level_3"),
                    ("2", "level_2"),
                    ("3", "level_1"),
                    ("4", "critical"),
                ],
                max_length=50,
            ),
        ),
    ]
