# Generated by Django 6.0.1 on 2026-02-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crime", "0004_alter_crime_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crime",
            name="committed_at",
        ),
        migrations.RemoveField(
            model_name="crime",
            name="description",
        ),
        migrations.RemoveField(
            model_name="crime",
            name="location",
        ),
        migrations.RemoveField(
            model_name="crime",
            name="title",
        ),
    ]
