# Generated by Django 6.0.1 on 2026-02-24 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crime", "0005_remove_crime_committed_at_remove_crime_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crimescene",
            name="case_report",
        ),
        migrations.RemoveField(
            model_name="crimescene",
            name="viewer",
        ),
        migrations.RemoveField(
            model_name="crimescene",
            name="witnesses",
        ),
        migrations.AddField(
            model_name="crimescene",
            name="crime",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crime_scenes",
                to="crime.crime",
            ),
        ),
        migrations.AddField(
            model_name="crimescene",
            name="witness",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="witnessed_scenes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="crimescene",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
