# Generated by Django 6.0.1 on 2026-02-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crime", "0006_remove_crimescene_case_report_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crime",
            name="level",
            field=models.IntegerField(
                choices=[
                    (1, "level_3"),
                    (2, "level_2"),
                    (3, "level_1"),
                    (4, "critical"),
                ]
            ),
        ),
    ]
