# Generated by Django 6.0.1 on 2026-02-26 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crime", "0007_alter_crime_level"),
        ("witness", "0004_alter_evidence_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="crimescene",
            name="testimony",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="crime_scene",
                to="witness.testimony",
            ),
        ),
    ]
