# Generated by Django 6.0.1 on 2026-02-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suspect", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suspectcrime",
            name="status",
            field=models.CharField(
                choices=[
                    ("suspect", "Suspect"),
                    ("wanted", "Wanted"),
                    ("most_wanted", "Most Wanted"),
                    ("arrested", "Arrested"),
                    ("convicted", "Convicted"),
                    ("innocent", "Innocent"),
                ],
                default="suspect",
                max_length=20,
            ),
        ),
    ]
