# Generated by Django 6.0.1 on 2026-02-26 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crime", "0007_alter_crime_level"),
        ("suspect", "0002_alter_suspectcrime_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suspectcrime",
            name="case",
        ),
        migrations.RemoveField(
            model_name="suspectcrime",
            name="priority_score",
        ),
        migrations.RemoveField(
            model_name="suspectcrime",
            name="reward_amount",
        ),
        migrations.RemoveField(
            model_name="suspectcrime",
            name="status",
        ),
        migrations.RemoveField(
            model_name="suspectcrime",
            name="wanted_since",
        ),
        migrations.RemoveField(
            model_name="suspectcrime",
            name="wanted_until",
        ),
        migrations.AddField(
            model_name="suspectcrime",
            name="crime",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suspects",
                to="crime.crime",
            ),
        ),
        migrations.CreateModel(
            name="Suspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("wanted", "Wanted"),
                            ("most_wanted", "Most Wanted"),
                            ("arrested", "Arrested"),
                            ("convicted", "Convicted"),
                            ("innocent", "Innocent"),
                        ],
                        default="wanted",
                        max_length=20,
                    ),
                ),
                ("priority_score", models.IntegerField(default=0)),
                ("reward_amount", models.BigIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspect",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="suspectcrime",
            name="suspect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suspected_crimes",
                to="suspect.suspect",
            ),
        ),
    ]
