# Generated by Django 6.0.1 on 2026-02-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suspect", "0003_remove_suspectcrime_case_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suspect",
            name="description",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="suspect",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("m", "Male"), ("f", "Female")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="suspect",
            name="name",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="suspect",
            name="national_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suspect",
            name="nickname",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="suspect",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="suspect"),
        ),
        migrations.AddField(
            model_name="suspect",
            name="wanted_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="suspect",
            name="status",
            field=models.CharField(
                choices=[
                    ("suspected", "Suspected"),
                    ("wanted", "Wanted"),
                    ("most_wanted", "Most Wanted"),
                    ("arrested", "Arrested"),
                    ("convicted", "Convicted"),
                    ("innocent", "Innocent"),
                ],
                default="suspected",
                max_length=20,
            ),
        ),
    ]
