# Generated by Django 6.0.1 on 2026-02-26 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crime", "0008_crimescene_testimony"),
        ("suspect", "0004_suspect_description_suspect_gender_suspect_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suspectcrime",
            name="crime",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="suspects",
                to="crime.crime",
            ),
            preserve_default=False,
        ),
    ]
