# Generated by Django 6.0.1 on 2026-02-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suspect", "0005_alter_suspectcrime_crime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="punishment",
            name="case",
        ),
    ]
