# Generated by Django 6.0.1 on 2026-02-26 19:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "factor_id",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                ("trans_id", models.CharField(blank=True, max_length=64, null=True)),
                ("id_get", models.CharField(blank=True, max_length=64, null=True)),
                ("amount", models.BigIntegerField()),
                ("mobile_num", models.CharField(blank=True, default="", max_length=15)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "card_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("is_success", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
