# Generated by Django 6.0.1 on 2026-02-26 19:25

import payment.models.transaction
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="factor_id",
            field=models.CharField(
                default=payment.models.transaction.generate_factor_id,
                max_length=12,
                unique=True,
            ),
        ),
    ]
