# Generated by Django 6.0.1 on 2026-02-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_alter_transaction_factor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
