# Generated by Django 6.0.1 on 2026-02-22 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="attachments")),
                (
                    "provided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IdentificationEvidence",
            fields=[
                (
                    "evidence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="witness.evidence",
                    ),
                ),
                ("owner_first_name", models.CharField(max_length=100)),
                ("owner_last_name", models.CharField(max_length=100)),
                ("information", models.JSONField(default=dict)),
            ],
            bases=("witness.evidence",),
        ),
        migrations.CreateModel(
            name="OtherEvidence",
            fields=[
                (
                    "evidence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="witness.evidence",
                    ),
                ),
            ],
            bases=("witness.evidence",),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BiologicalEvidence",
            fields=[
                (
                    "evidence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="witness.evidence",
                    ),
                ),
                ("result", models.TextField(blank=True, null=True)),
                (
                    "coronary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coronary_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="biological_evidence", to="witness.image"
                    ),
                ),
            ],
            bases=("witness.evidence",),
        ),
        migrations.CreateModel(
            name="Testimony",
            fields=[
                (
                    "evidence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="witness.evidence",
                    ),
                ),
                ("transcription", models.TextField()),
                ("attachments", models.ManyToManyField(to="witness.attachment")),
            ],
            bases=("witness.evidence",),
        ),
        migrations.CreateModel(
            name="VehicleEvidence",
            fields=[
                (
                    "evidence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="witness.evidence",
                    ),
                ),
                ("vehicle_model", models.CharField(max_length=50)),
                (
                    "registration_plate_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("color", models.CharField(max_length=50)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("serial_number__isnull", False),
                                ("registration_plate_number__isnull", True),
                            ),
                            models.Q(
                                ("serial_number__isnull", True),
                                ("registration_plate_number__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="exactly_one_of_serial_or_plate",
                    )
                ],
            },
            bases=("witness.evidence",),
        ),
    ]
