# Generated by Django 6.0.1 on 2026-02-22 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crime", "0004_alter_crime_level"),
        ("witness", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="case",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="crime.case",
            ),
            preserve_default=False,
        ),
    ]
