# Generated by Django 6.0.1 on 2026-02-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("witness", "0002_evidence_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="location",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evidence",
            name="seen_at",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testimony",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
