# Generated by Django 6.0.1 on 2026-02-25 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crime", "0006_remove_crimescene_case_report_and_more"),
        ("witness", "0003_evidence_location_evidence_seen_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="crime.case",
            ),
        ),
    ]
