# Generated by Django 6.0.1 on 2026-02-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reward", "0002_reporter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="processed_by",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="reward",
        ),
        migrations.DeleteModel(
            name="Reporter",
        ),
        migrations.RemoveField(
            model_name="report",
            name="detective_rejection_reason",
        ),
        migrations.RemoveField(
            model_name="report",
            name="officer_rejection_reason",
        ),
        migrations.RemoveField(
            model_name="reward",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="reward",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="reward",
            name="recipient",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
