# Generated by Django 6.0.1 on 2026-02-26 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reward", "0003_remove_payment_processed_by_remove_payment_reward_and_more"),
        ("suspect", "0004_suspect_description_suspect_gender_suspect_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="suspect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tips",
                to="suspect.suspect",
            ),
        ),
    ]
