# Generated by Django 6.0.1 on 2026-02-26 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reward", "0004_add_reward_recipient_amount_created_by"),
        ("reward", "0004_alter_report_suspect"),
    ]

    operations = []
