# Generated by Django 6.0.1 on 2026-01-11 17:58

from django.db import migrations


def add_roles(apps, schema_editor):
    role_model = apps.get_model('user', 'Role')
    role_title = [
        'Administrator',
        'Chief',
        'Captain',
        'Sergent',
        'Detective',
        'Police Officer',
        'Patrol Officer',
        'Cadet',
        'Complainant',
        'Witness',
        'Suspect',
        'Criminal',
        'Judge',
        'Coronary',
        'Base User',
    ]
    for title in role_title:
        role_model.objects.create(title=title)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_roles)
    ]
