# Generated by Django 6.0.1 on 2026-02-22 15:52

import user.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20260111_2128"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user.models.user.CustomUserManager()),
            ],
        ),
    ]
