# Generated by Django 6.0.1 on 2026-02-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0004_alter_user_options_alter_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_username_if_not_null",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_email_if_not_null",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_phone_if_not_null",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_national_id_if_not_null",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("username__isnull", True), _negated=True),
                    models.Q(("username", ""), _negated=True),
                ),
                fields=("username",),
                name="unique_username_if_not_null_or_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("email__isnull", True), _negated=True),
                    models.Q(("email", ""), _negated=True),
                ),
                fields=("email",),
                name="unique_email_if_not_null_or_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("phone__isnull", True), _negated=True),
                    models.Q(("phone", ""), _negated=True),
                ),
                fields=("phone",),
                name="unique_phone_if_not_null_or_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("national_id__isnull", True), _negated=True),
                    models.Q(("national_id", ""), _negated=True),
                ),
                fields=("national_id",),
                name="unique_national_id_if_not_null_or_empty",
            ),
        ),
    ]
