from .suspect_crime_views import SuspectCrimeViewSet, WantedSuspectsView
from .interrogation_views import InterrogationViewSet, SubmitScoreView, ReviewInterrogationView
from .punishment_views import PunishmentViewSet, IssuePunishmentView, ProcessPaymentView
